services:
  open-ledger:
    tty: true
    image: open-ledger
    stdin_open: true
    build:
      context: .
      target: "development"
    volumes:
      - ".:/src"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file: .env
    environment:
      TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
    ports:
      - "8000:8000"
    depends_on:
      - open-ledger-db
  open-ledger-db:
    image: postgres:13.3-alpine
    volumes:
      - open_ledger_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: open_ledger_db
    ports:
      - "5433:5432"
volumes:
  open_ledger_db:
